[package]
name = "geo-plot"
version = "0.1.0"
authors = ["tsturzl <tsturzl@lefthandrobotics.com>"]
edition = "2018"
description = "Plot geo_types with gnuplot"
license = "MIT"

[dependencies]
geo-types = "0.4.3"
gnuplot = "0.0.33"
